# Generated by Django 2.2.2 on 2020-07-27 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('profile_pic', models.ImageField(null=True, upload_to='profile/')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phonenumber', models.CharField(max_length=13)),
                ('AccountNumber', models.CharField(max_length=15)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_title', models.TextField(max_length=20)),
                ('days', models.DateTimeField()),
                ('opening_hours', models.DateTimeField()),
                ('age', models.CharField(max_length=3)),
                ('max_persons', models.CharField(max_length=20)),
                ('discount_per_person', models.CharField(max_length=50)),
                ('group_discount_per_person', models.CharField(max_length=50)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('guests', models.CharField(max_length=8)),
                ('bedrooms', models.CharField(max_length=8)),
                ('beds', models.CharField(max_length=8)),
                ('baths', models.CharField(max_length=8)),
                ('toilets', models.CharField(max_length=8)),
                ('more_details', models.TextField(max_length=200)),
                ('checkin', models.TimeField(auto_now_add=True)),
                ('checkout', models.TimeField(auto_now_add=True)),
                ('discount_per_person', models.CharField(max_length=50)),
                ('group_discount_per_person', models.CharField(max_length=50)),
                ('activity_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='easyway.activities')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='rent_car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=200)),
                ('add_photos', models.ImageField(null=True, upload_to='cars/')),
                ('more_details', models.TextField(max_length=200)),
                ('place_available', models.TextField(verbose_name=20)),
                ('discount_per_person', models.CharField(max_length=50)),
                ('activity_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='easyway.activities')),
            ],
        ),
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=20, null=True)),
                ('activity_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='easyway.activities')),
                ('car_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='easyway.rent_car')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='easyway.hotel')),
            ],
        ),
    ]
