# Generated by Django 2.2.2 on 2020-07-10 14:02

from django.db import migrations

def create_data(apps, schema_editor):
    easyway = apps.get_model('easyway', 'customers')
    easyway(username="Joseph", first_name="Joseph", last_name="Njogu", \
    email="josephnjogu@email.com", phonenumber= 719673694,\
    AccountNumber=444444444444).save()


class Migration(migrations.Migration):

    dependencies = [
        ('easyway', '0002_auto_20200707_1608'),
    ]

    operations = [
       migrations.RunPython(create_data),
    ]
