# Generated by Django 2.2.2 on 2020-07-13 11:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('easyway', '0004_auto_20200713_1146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='activity',
            new_name='activities',
        ),
        migrations.RenameModel(
            old_name='customer',
            new_name='customers',
        ),
    ]
