# Generated by Django 2.2.2 on 2020-07-13 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easyway', '0005_auto_20200713_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='easyway.customers'),
        ),
    ]
