# Generated by Django 2.2.2 on 2020-07-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easyway', '0007_auto_20200717_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='No_of_baths',
            new_name='baths',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='No_of_bedrooms',
            new_name='bedrooms',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='No_of_beds',
            new_name='beds',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='No_of_guests',
            new_name='guests',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='No_of_toilets',
            new_name='toilets',
        ),
        migrations.AddField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.TextField(max_length=20, null=True)),
                ('activity_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='easyway.activities')),
                ('car_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='easyway.rent_car')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='easyway.hotel')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='easyway.customers')),
            ],
        ),
    ]
